import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen px-4 sm:px-6 md:px-8 pt-4 sm:pt-6 md:pt-8 pb-32 sm:pb-40 md:pb-48 max-w-[1440px] mx-auto`}
      >
        <ClientWrapper>
          <Header />
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
